    
---
- name: Install Redhat dependencies
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - gcc
    - make
  when:
    - ansible_os_family == "RedHat"

- name: install debian dependencies
  apt:
    pkg:
      - gcc
      - make
      - libc6-dev
    update_cache: yes
    cache_valid_time: 86400
    state: present
  when: ansible_os_family == "Debian"